const pages=[['index.html','Главная'],['all-services.html','Услуги'],['services.html','Программа'],['prices.html','Цены'],['gallery.html','Фото'],['promotions.html','Акции'],['reviews.html','Отзывы'],['contacts.html','Контакты']];
const file=(location.pathname.split('/').pop()||'index.html').toLowerCase();
if(!document.querySelector('link[rel~="icon"]'))document.head.insertAdjacentHTML('beforeend','<link rel="icon" href="favicon.ico" sizes="any">');
const gardenPhotos=[
  'assets/references/hero-reference.png','assets/references/adaptation-reference.png','assets/references/classroom-reference.png','assets/references/art-reference.png','assets/references/cooking-reference.png','assets/references/music-reference.png','assets/references/team-reference.png','assets/references/director-reference.png','assets/references/educator-reference.png','assets/references/food-reference.png','assets/references/reading-reference.png','assets/references/entrance-reference.png'
];
const logoMarkup=`<svg class="logo-art logo-desktop" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1400 440" aria-hidden="true" focusable="false"><g transform="translate(40 35)"><circle fill="#F3D56B" cx="118" cy="90" r="48"/><g fill="#F3D56B"><rect x="112" y="14" width="12" height="34" rx="6"/><rect x="52" y="79" width="34" height="12" rx="6"/><rect x="150" y="79" width="34" height="12" rx="6"/><rect x="72" y="32" width="12" height="30" rx="6" transform="rotate(-45 78 47)"/><rect x="152" y="34" width="12" height="30" rx="6" transform="rotate(45 158 49)"/></g><path fill="#8EC29D" d="M38 286c18-52 67-82 121-82s103 30 121 82H38z"/><path d="M160 248c-5-67 12-111 38-149" fill="none" stroke="#6FA486" stroke-width="17" stroke-linecap="round"/><path fill="#8EC29D" d="M156 184c-48 0-81-23-96-65 45 0 81 22 96 65z"/><path fill="#6FA486" d="M177 148c11-50 43-80 89-88-6 46-36 78-89 88z"/></g><g font-family="Manrope,Onest,Inter,Arial,sans-serif" font-weight="700" transform="translate(350 120)"><text x="0" y="0" font-size="106" fill="#6FA486">Сад</text><text x="0" y="118" font-size="96" fill="#2F3A34">Монтессори</text><text x="4" y="175" font-size="42" letter-spacing=".06em" fill="#6FA486">ЖУЛЕБИНО</text></g></svg><svg class="logo-art logo-mobile" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 760" aria-hidden="true" focusable="false"><g transform="translate(180 55)"><circle fill="#F3D56B" cx="118" cy="90" r="52"/><g fill="#F3D56B"><rect x="112" y="10" width="12" height="38" rx="6"/><rect x="48" y="80" width="38" height="12" rx="6"/><rect x="152" y="80" width="38" height="12" rx="6"/><rect x="68" y="30" width="12" height="34" rx="6" transform="rotate(-45 74 47)"/><rect x="156" y="34" width="12" height="34" rx="6" transform="rotate(45 162 51)"/></g><path fill="#8EC29D" d="M28 300c22-56 75-88 131-88s109 32 131 88H28z"/><path d="M164 262c-5-70 12-118 42-160" fill="none" stroke="#6FA486" stroke-width="18" stroke-linecap="round"/><path fill="#8EC29D" d="M156 192c-52 0-88-26-103-71 48 0 87 24 103 71z"/><path fill="#6FA486" d="M182 154c12-54 48-86 97-95-6 50-40 84-97 95z"/></g><g font-family="Manrope,Onest,Inter,Arial,sans-serif" font-weight="700" text-anchor="middle" transform="translate(380 485)"><text x="0" y="0" font-size="92" fill="#6FA486">Сад</text><text x="0" y="104" font-size="82" fill="#2F3A34">Монтессори</text><text x="0" y="158" font-size="38" letter-spacing=".05em" fill="#6FA486">ЖУЛЕБИНО</text></g></svg>`;
const responsiveLogoMarkup=logoMarkup.replace(/<svg class="logo-art logo-mobile"[\s\S]*?<\/svg>$/,`<img class="logo-art logo-mobile" src="assets/brand/logo-sad-montessori-mobile-horizontal.svg" alt="Сад Монтессори — Жулебино">`);
document.querySelectorAll('[data-header]').forEach(el=>el.innerHTML=`<a class="skip-link" href="#main">К основному содержанию</a><header class="site-header"><div class="container header-row"><a class="brand brand-logo" href="index.html" aria-label="Сад Монтессори в Жулебино — главная">${responsiveLogoMarkup}</a><button class="menu-btn" aria-label="Открыть меню" aria-expanded="false" aria-controls="site-nav">☰</button><nav class="nav" id="site-nav" aria-label="Основная навигация">${pages.map(([url,label])=>`<a class="${file===url?'active':''}" href="${url}"${file===url?' aria-current="page"':''}>${label}</a>`).join('')}</nav><a class="phone" href="tel:+79264835949">+7 (926) 483-59-49</a><a class="btn" href="contacts.html#tour">На экскурсию</a></div></header>`);
document.querySelector('main')?.setAttribute('id','main');
document.querySelectorAll('[data-footer]').forEach(el=>el.innerHTML=`<footer class="site-footer"><div class="container footer-grid"><div><a class="brand brand-logo footer-logo" href="index.html" aria-label="Сад Монтессори в Жулебино — главная">${responsiveLogoMarkup}</a><p>Частный детский сад для детей от 1,5 до 7 лет.</p><p class="fine">Стоимость и наличие мест уточняйте у администратора. Информация на сайте не является публичной офертой.</p></div><div class="footer-links"><strong>Разделы</strong>${pages.slice(1).map(([u,l])=>`<a href="${u}">${l}</a>`).join('')}</div><div><strong>Контакты</strong><p><a href="tel:+79264835949">+7 (926) 483-59-49</a><br>Москва, ул. Авиаконструктора Миля, 11, корп. 1<br>Пн–пт, 08:00–19:00</p><p><a href="privacy.html">Политика обработки данных</a></p></div></div></footer><div class="mobile-cta"><a class="btn secondary" href="tel:+79264835949">Позвонить</a><a class="btn" href="contacts.html#tour">Экскурсия</a></div>`);
document.addEventListener('click',e=>{if(e.target.closest('.menu-btn')){const b=e.target.closest('.menu-btn'),n=document.querySelector('.nav');n.classList.toggle('open');b.setAttribute('aria-expanded',n.classList.contains('open'))}});
document.querySelectorAll('.mail-form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);const subject=encodeURIComponent('Заявка на экскурсию — Сад Монтессори');const body=encodeURIComponent(`Имя родителя: ${d.get('name')}\nТелефон: ${d.get('phone')}\nВозраст ребёнка: ${d.get('age')||'не указан'}\nКомментарий: ${d.get('message')||'—'}`);location.href=`mailto:kirillmol@mail.ru?subject=${subject}&body=${body}`;}));
document.querySelectorAll('.mail-form input,.mail-form select,.mail-form textarea').forEach(field=>{if(!field.getAttribute('aria-label'))field.setAttribute('aria-label',field.placeholder||({name:'Имя родителя',phone:'Телефон',age:'Возраст ребёнка',message:'Комментарий'}[field.name]||field.name));});
if(file==='index.html'){
  const reviews=[...document.querySelectorAll('.section')].find(s=>s.textContent.includes('Что говорят родители'));
  if(reviews){reviews.classList.remove('tint');reviews.insertAdjacentHTML('beforebegin',`<section class="section tint"><div class="container"><div class="section-head"><div><div class="eyebrow">Ритм без спешки</div><h2>День, в котором есть место выбору</h2></div><p>Занятия сменяют друг друга без гонки: ребёнок успевает сосредоточиться, подвигаться, пообщаться и отдохнуть.</p></div><div class="timeline"><div class="timeline-item"><div class="timeline-time">Встреча</div><strong>Спокойно войти в день</strong><p>Педагог помогает ребёнку освоиться и выбрать первое занятие.</p></div><div class="timeline-item"><div class="timeline-time">Montessori-класс</div><strong>Работа в своём темпе</strong><p>Ребёнок выбирает материал, действует самостоятельно и при необходимости получает помощь.</p></div><div class="timeline-item"><div class="timeline-time">Вместе</div><strong>Движение и общение</strong><p>В дне есть групповые занятия, творчество, музыка и время быть с другими детьми.</p></div><div class="timeline-item"><div class="timeline-time">Завершение</div><strong>Спокойный переход домой</strong><p>Родителям рассказывают о важных событиях и настроении ребёнка.</p></div></div></div></section>`);}
}
const photoPlan={'index.html':[0,1],'gallery.html':[2,8,9,3,5,4,6,10,11],'services.html':[7,8,6]};
const photoLabels=['Ребёнок занимается в Montessori-среде','Знакомство ребёнка с педагогом','Пространство Montessori-класса','Живопись на мольбертах','Кулинарное занятие','Музыкальное занятие','Команда детского сада','Руководитель беседует с родителем','Педагог помогает ребёнку','Сервировка детского стола','Время для чтения','Вход в детский сад'];
const photoSizes=[[1536,1024],[1448,1086],[1448,1086],[1448,1086],[1448,1086],[1448,1086],[1536,1024],[1122,1402],[1122,1402],[1448,1086],[1448,1086],[1536,1024]];
document.head.insertAdjacentHTML('beforeend','<style>.media-placeholder.has-photo{position:relative;overflow:hidden;padding:0;background:var(--sage);border:0}.media-placeholder.has-photo img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.media-placeholder.has-photo .photo-fallback{display:none}</style>');
(photoPlan[file]||[]).forEach((photoIndex,slot)=>{
  const box=document.querySelectorAll('.media-placeholder')[slot];
  if(!box)return;
  const fallback=box.innerHTML;
  const label=box.querySelector('b')?.textContent||'Фотография Сада Монтессори';
  const eager=file==='index.html'&&slot===0;
  box.classList.add('has-photo');
  box.innerHTML=`<div class="photo-fallback">${fallback}</div><img src="${gardenPhotos[photoIndex]}" alt="${photoLabels[photoIndex]}" width="${photoSizes[photoIndex][0]}" height="${photoSizes[photoIndex][1]}" sizes="(max-width: 680px) 100vw, (max-width: 980px) 50vw, 40vw" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
  const img=box.querySelector('img');
  img.addEventListener('load',()=>box.classList.add('photo-loaded'));
  img.addEventListener('error',()=>box.classList.add('photo-error'));
  if(img.complete&&img.naturalWidth)box.classList.add('photo-loaded');
});
const header=document.querySelector('.site-header');
const backToTop=document.createElement('button');
backToTop.className='back-to-top';
backToTop.type='button';
backToTop.setAttribute('aria-label','Вернуться в начало страницы');
backToTop.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 19V5M6.5 10.5 12 5l5.5 5.5"/></svg>';
document.body.append(backToTop);
const updateScrollUi=()=>{
  const moved=window.scrollY>48;
  header?.classList.toggle('is-scrolled',moved);
  backToTop.classList.toggle('is-visible',window.scrollY>520);
};
window.addEventListener('scroll',updateScrollUi,{passive:true});
backToTop.addEventListener('click',()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}));
updateScrollUi();

